###########################################################################
#
# Generated by : Version 9.1 Build 222 10/21/2009 SJ Full Version
#
# Project      : svm
# Revision     : svm
#
# Date         : Mon Oct 30 14:21:19 AST 2017
#
###########################################################################
 
 
#
# ------------------------------------------
#
# Create generated clocks based on PLLs
derive_pll_clocks -use_tan_name
#
# ------------------------------------------
# WARNING: Global Fmax translated to derive_clocks. Behavior is not identical
if {![info exist ::qsta_message_posted]} {
    post_message -type warning "Original Global Fmax translated from QSF using derive_clocks"
    set ::qsta_message_posted 1
}
derive_clocks -period "40 MHz"
#


# Original Clock Setting Name: clk
create_clock -period "50.000 ns" \
             -name {clk} {clk}
# ---------------------------------------------


# Original Clock Setting Name: new_cycle
create_clock -period "200000.000 ns" \
             -waveform { 0 20000.0 } \
             -name {new_cycle} {new_cycle}
# ---------------------------------------------

# ** Clock Latency
#    -------------

# ** Clock Uncertainty
#    -----------------

# ** Multicycles
#    -----------
# ** Cuts
#    ----

# ** Input/Output Delays
#    -------------------




# ** Tpd requirements
#    ----------------

# ** Setup/Hold Relationships
#    ------------------------

# ** Tsu/Th requirements
#    -------------------


# ** Tco/MinTco requirements
#    -----------------------

#
# Entity Specific Timing Assignments found in
# the Timing Analyzer Settings report panel
#


# ---------------------------------------------
# The following clock group is added to try to 
# match the behavior of:
#   CUT_OFF_PATHS_BETWEEN_CLOCK_DOMAINS = ON
# ---------------------------------------------

set_clock_groups -asynchronous \
                 -group { \
                       new_cycle \
                        } \
                 -group { \
                       clk \
                        } \

# ---------------------------------------------

